title: notenoughrants
description: >
  A deposit of various rants about technology, software engineering 
  and other stuff I feel like writing about

url: http://notenoughrants.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: jeremangnr
   twitter: jereahrequesi
   facebook: jereee.n
   email: jeremias.np@gmail.com
   linkedin: jeremiasnp

google_analytics: "UA-65241739-1"
